config/routes.rb
Rails.application.routes.draw do
  get 'ccsf_rails/index'

  get 'ccsf_rails/links'

  get 'ccsf_rails/about'

  root 'ccsf_rails#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   
    #do your stuff with comments_from_form here
  protect_from_forgery with: :exception
end

app/controllers/ccsf_rails_controller.rb
class CcsfRailsController < ApplicationController
  def index

  end

  def links
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ccsf_rails_helper.rb
module CcsfRailsHelper
end

app/views/ccsf_rails/about.html.erb
<div class="menu">
	<ul>
		<li><%= link_to 'Home', ccsf_rails_index_path(@index) %></li> |
		<li><%= link_to 'About', ccsf_rails_about_path(@about) %></li> |
		<li><%= link_to 'Links', ccsf_rails_links_path(@links) %></li>
	</ul>
</div>

<div class="welcome">
	<h1>About</h1>
	<p>This is a test website. I'm practicing Ruby code.</p>
</div>

<div id="footer">

		<%= link_to 'Home', ccsf_rails_index_path(@index) %> | <%= link_to 'About', ccsf_rails_about_path(@about) %> | <%= link_to 'Links', ccsf_rails_links_path(@links) %>

</div>

app/views/ccsf_rails/index.html.erb
<div class="menu">
	<ul>
		<li><%= link_to 'Home', ccsf_rails_index_path(@index) %></li> | 
		<li><%= link_to 'About', ccsf_rails_about_path(@about) %></li> |
		<li><%= link_to 'Links', ccsf_rails_links_path(@links) %></li>
	</ul>
</div>

<div class="welcome">
	<h1>Welcome!</h1>
	<p>to Bill's first Ruby on Rails website!</p>
	<p>Here's a test link: <a href="http://www.google.com">Google</a></p>

</div>


<div id="footer">
		<%= link_to 'Home', ccsf_rails_index_path(@index) %> | <%= link_to 'About', ccsf_rails_about_path(@about) %> | <%= link_to 'Links', ccsf_rails_links_path(@links) %>

</div>

app/views/ccsf_rails/links.html.erb
<div class="menu">
	<ul>
		<li><%= link_to 'Home', ccsf_rails_index_path(@index) %></li> |
		<li><%= link_to 'About', ccsf_rails_about_path(@about) %></li> |
		<li><%= link_to 'Links', ccsf_rails_links_path(@links) %></li>
	</ul>
</div>

<div class="welcome"><h1>Links</h1>
	<p>Why would you want to go anywhere else?</p>
</div>

<div id="footer">
		<%= link_to 'Home', ccsf_rails_index_path(@index) %> | <%= link_to 'About', ccsf_rails_about_path(@about) %> | <%= link_to 'Links', ccsf_rails_links_path(@links) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>